resource_group_name = "az-rg-resources"
location            = "West Europe"
storage_account_type = "Standard_LRS"
size                = "Standard_F2"
username            = "lmadmin"
password            = "P@$$w0rd1234567@@!"
account_tier             = "Standard"
account_replication_type = "LRS"